name       : docker
version    : 1.12.3
release    : 4
source     :
    - https://github.com/docker/docker/archive/v1.12.3.tar.gz : cf4f876593abde06b4c19f971163a853a21b1992d75bd2fe5d8bea9015b09f87
license    : Apache-2.0
component  : virt
summary    : Open source application container engine
strip      : no
description: |
    Docker is an open source project to pack, ship and run any application as a lightweight container.

    Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to the largest cloud compute instance and everything in between - and they don't require you to use a particular language, framework or packaging system. That makes them great building blocks for deploying and scaling web apps, databases, and backend services without depending on a particular stack or provider.
builddeps  :
    - btrfs-progs-devel
    - golang
    - pkgconfig(devmapper)
rundeps    :
    - btrfs-progs
    - containerd
    - dnsmasq
    - runc
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-to-using-overlayfs.patch
build      : |
    export DOCKER_GITCOMMIT="23cf638307f030cd8d48c9efc21feec18a6f88f8"
    export AUTO_GOPATH=1
    ./hack/make.sh dynbinary
install    : |
    # Required directories
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00755 $installdir/%libdir%/systemd/system

    # Install docker client
    install -m 00755 bundles/${version}/dynbinary-client/docker-${version} $installdir/usr/bin/docker

    # Now install proxy service
    install -m 00755 bundles/${version}/dynbinary-daemon/docker-proxy-${version} $installdir/usr/bin/docker-proxy

    # Main docker daemon
    install -m 00755 bundles/${version}/dynbinary-daemon/dockerd-${version} $installdir/usr/bin/dockerd

    # Now install systemd units
    install -m 00644 contrib/init/systemd/docker.service $installdir/%libdir%/systemd/system/.
    install -m 00644 contrib/init/systemd/docker.socket $installdir/%libdir%/systemd/system/.

    # Enable socket activation by default
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../docker.socket $installdir/%libdir%/systemd/system/sockets.target.wants/docker.socket

    # Add the docker group
    install -D -m 00644 $pkgfiles/docker.sysusers $installdir/%libdir%/sysusers.d/docker.conf

    # containerd integration:
    ln -s containerd $installdir/usr/bin/docker-containerd
    ln -s containerd-shim $installdir/usr/bin/docker-containerd-shim
    ln -s ctr $installdir/usr/bin/docker-containerd-ctr
    ln -s runc $installdir/usr/bin/docker-runc
