name       : docker
version    : 19.03.14
release    : 30
source     :
    - https://github.com/docker/docker-ce/archive/v19.03.14.tar.gz : 0b8838b0da1f1368fc1a0809a2ed11840bd7d58df1f090e668de209faddcef7c
    - git|https://github.com/docker/libnetwork.git : 55e924b8a84231a065879156c0de95aefc5f5435
    - git|https://github.com/krallin/tini.git : v0.19.0
license    : Apache-2.0
component  : virt
summary    : Open source application container engine
description: |
    Docker is an open source project to pack, ship and run any application as a lightweight container.

    Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to the largest cloud compute instance and everything in between - and they don't require you to use a particular language, framework or packaging system. That makes them great building blocks for deploying and scaling web apps, databases, and backend services without depending on a particular stack or provider.
strip      : no
builddeps  :
    - pkgconfig(devmapper)
    - btrfs-progs-devel
    - go-md2man
    - golang
rundeps    :
    - btrfs-progs
    - containerd
    - dnsmasq
    - runc
build      : |
    mkdir -p src/github.com/docker
    export GOPATH=`pwd`
    unset LDFLAGS

    # Build proxy
    ln -sv $sources/libnetwork.git src/github.com/docker/libnetwork
    go build -o docker-proxy github.com/docker/libnetwork/cmd/proxy
    rm -v src/github.com/docker/libnetwork

    # Build daemon
    export VERSION=${version}-ce
    pushd components/engine
    export DOCKER_GITCOMMIT="4484c46d9d1a2d10b8fc662923ad586daeedb04f"
    export GITCOMMIT="4484c46d9d1a2d10b8fc662923ad586daeedb04f"
    export AUTO_GOPATH=1
    ./hack/make.sh dynbinary
    popd

    # Build docker-init
    mkdir -p src/github.com/krallin/tini
    cp -r $sources/tini.git/* src/github.com/krallin/tini/
    pushd src/github.com/krallin/tini
    %cmake .
    %make tini-static
    popd

    # Build CLI
    ln -sv `pwd`/components/cli src/github.com/docker
    pushd components/cli
    ./scripts/build/dynbinary
    popd

    # Build manpages
    components/cli/man/md2man-all.sh
install    : |
    # Required directories
    install -Ddm00755 $installdir/usr/bin
    install -Ddm00755 $installdir/%libdir%/systemd/system

    # Install docker client
    pushd components/cli
    install -m00755 build/docker-linux-amd64 $installdir/usr/bin/docker
    popd

    # Main docker daemon
    pushd components/engine
    install -m00755 bundles/dynbinary-daemon/dockerd-${version}-ce $installdir/usr/bin/dockerd
    popd

    # Now install docker-init
    install -m00755 $workdir/src/github.com/krallin/tini/tini-static $installdir/usr/bin/docker-init

    # Now install proxy service
    install -m00755 $workdir/docker-proxy $installdir/usr/bin/docker-proxy

    # Now install systemd units
    install -m00644 components/engine/contrib/init/systemd/docker.service $installdir/%libdir%/systemd/system/.
    install -m00644 components/engine/contrib/init/systemd/docker.socket $installdir/%libdir%/systemd/system/.

    # Enable socket activation by default
    install -Ddm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../docker.socket $installdir/%libdir%/systemd/system/sockets.target.wants/docker.socket

    # Add the docker group
    install -Dm00644 $pkgfiles/docker.sysusers $installdir/%libdir%/sysusers.d/docker.conf

    # containerd integration
    ln -s containerd $installdir/usr/bin/docker-containerd
    ln -s containerd-shim $installdir/usr/bin/docker-containerd-shim
    ln -s ctr $installdir/usr/bin/docker-containerd-ctr
    ln -s runc $installdir/usr/bin/docker-runc

    # Install completions
    install -Dm00644 components/cli/contrib/completion/bash/docker $installdir/usr/share/bash-completion/completions/docker
    install -Dm00644 components/cli/contrib/completion/zsh/_docker $installdir/usr/share/zsh/site-functions/_docker

    # Install manpages
    for i in 1 5 8; do
      install -Dm00644 components/cli/man/man$i/*.$i -t $installdir/usr/share/man/man$i
    done
