name       : docker
version    : 20.10.7
release    : 33
source     :
    - https://github.com/moby/moby/archive/v20.10.7.tar.gz : b80142035de46904605fb7b8f18075cd94154f8c3d67ff346ea554d1e9d579b9
    - git|https://github.com/docker/cli : v20.10.7
    - git|https://github.com/docker/libnetwork.git : 64b7a4574d1426139437d20e81c0b6d391130ec8
    - git|https://github.com/krallin/tini.git : v0.19.0
license    : Apache-2.0
component  : virt
summary    : Open source application container engine
description: |
    Docker is an open source project to pack, ship and run any application as a lightweight container.

    Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to the largest cloud compute instance and everything in between - and they don't require you to use a particular language, framework or packaging system. That makes them great building blocks for deploying and scaling web apps, databases, and backend services without depending on a particular stack or provider.
strip      : no
builddeps  :
    - pkgconfig(devmapper)
    - btrfs-progs-devel
    - go-md2man
    - golang
rundeps    :
    - btrfs-progs
    - containerd
    - dnsmasq
    - runc
environment: |
    export AUTO_GOPATH=1
    export DOCKER_GITCOMMIT="363e9a88a11be517d9e8c65c998ff56f774eb4dc"
    export GITCOMMIT="363e9a88a11be517d9e8c65c998ff56f774eb4dc"
    export GO111MODULE=auto
    export GOPATH="${workdir}"
    unset LDFLAGS
build      : |
    mkdir -p src/github.com/docker

    # Build proxy
    ln -sv $sources/libnetwork.git src/github.com/docker/libnetwork
    go build -o $workdir/docker-proxy github.com/docker/libnetwork/cmd/proxy
    rm -v src/github.com/docker/libnetwork

    # Build daemon
    export VERSION=${version}-ce
    ./hack/make.sh dynbinary

    # Build docker-init
    mkdir -p src/github.com/krallin/tini
    cp -r $sources/tini.git/* src/github.com/krallin/tini/
    pushd src/github.com/krallin/tini
    %cmake .
    %make tini-static
    popd

    # Build CLI
    mkdir -p src/github.com/docker/cli
    cp -R $sources/cli.git/* src/github.com/docker/cli/
    pushd src/github.com/docker/cli/
    %make dynbinary
    popd

    # Build manpages
    pushd src/github.com/docker/cli
    ./man/md2man-all.sh
    popd
install    : |
    # Required directories
    install -Ddm00755 $installdir/usr/bin
    install -Ddm00755 $installdir/%libdir%/systemd/system

    # Install docker client
    install -m00755 src/github.com/docker/cli/build/docker-linux-amd64 $installdir/usr/bin/docker

    # Main docker daemon
    install -m00755 bundles/dynbinary-daemon/dockerd-${version}-ce $installdir/usr/bin/dockerd

    # Now install docker-init
    install -m00755 $workdir/src/github.com/krallin/tini/tini-static $installdir/usr/bin/docker-init

    # Now install proxy service
    install -m00755 $workdir/docker-proxy $installdir/usr/bin/docker-proxy

    # Now install systemd units
    install -m00644 contrib/init/systemd/docker.service $installdir/%libdir%/systemd/system/.
    install -m00644 contrib/init/systemd/docker.socket $installdir/%libdir%/systemd/system/.

    # Enable socket activation by default
    install -Ddm00755 $installdir/%libdir%/systemd/system/sockets.target.wants
    ln -sv ../docker.socket $installdir/%libdir%/systemd/system/sockets.target.wants/docker.socket

    # Add the docker group
    install -Dm00644 $pkgfiles/docker.sysusers $installdir/%libdir%/sysusers.d/docker.conf

    # containerd integration
    ln -s containerd $installdir/usr/bin/docker-containerd
    ln -s containerd-shim $installdir/usr/bin/docker-containerd-shim
    ln -s ctr $installdir/usr/bin/docker-containerd-ctr
    ln -s runc $installdir/usr/bin/docker-runc

    # Install completions
    pushd src/github.com/docker/cli
    install -Dm00644 contrib/completion/bash/docker $installdir/usr/share/bash-completion/completions/docker
    install -Dm00644 contrib/completion/zsh/_docker $installdir/usr/share/zsh/site-functions/_docker

    # Install manpages
    for i in 1 5 8; do
      install -Dm00644 man/man$i/*.$i -t $installdir/usr/share/man/man$i
    done
    popd
