name       : docker
version    : 24.0.5
release    : 46
source     :
    - https://github.com/docker/cli/archive/refs/tags/v24.0.5.tar.gz : fa32b5f3c2f85fba9ef6e1b5099a4b608fa20af45ba71b3da2194e8728037eec
license    : Apache-2.0
component  : virt
summary    : Open source application container engine
description: |
    Docker is an open source project to pack, ship and run any application as a lightweight container.

    Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to the largest cloud compute instance and everything in between - and they don't require you to use a particular language, framework or packaging system. That makes them great building blocks for deploying and scaling web apps, databases, and backend services without depending on a particular stack or provider.
strip      : no
networking : yes
builddeps  :
    - go-md2man
    - golang
rundeps    :
    - docker-buildx
    - moby
environment: |
    export GITCOMMIT="ced099660009713e0e845eeb754e6050dbaa45d0"
    export DOCKER_GITCOMMIT=$GITCOMMIT
    export DISABLE_WARN_OUTSIDE_CONTAINER=1

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"

    export GO111MODULE=auto
setup      : |
    mkdir -p src/github.com/docker/
    ln -s `pwd` src/github.com/docker/cli
build      : |
    cd src/github.com/docker/cli
    export GOPATH=`pwd`

    # Build CLI
    PLATFORM="Docker Engine - Community" \
    VERSION=${version} \
        make dynbinary

    # man pages
    make manpages
install    : |
    # Install docker client
    install -Dm00755 build/docker-linux-amd64 $installdir/usr/bin/docker

    install -Dm00644 man/man1/*.1 -t $installdir/usr/man/man1
    install -Dm00644 man/man5/*.5 -t $installdir/usr/man/man5

    # Install completions
    install -Dm00644 contrib/completion/bash/docker $installdir/usr/share/bash-completion/completions/docker
    install -Dm00644 contrib/completion/zsh/_docker $installdir/usr/share/zsh/site-functions/_docker
    install -Dm00644 contrib/completion/fish/docker.fish $installdir/usr/share/fish/vendor_completions.d/docker.fish

    # Install nanorc
    install -Dm00644 $pkgfiles/Dockerfile.nanorc -t $installdir/usr/share/nano/
